name: Netlify Build

on:
  schedule:
    - cron: '00 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          NETLIFY_DEPLOY_HOOK: ${{ secrets.NetlifyDeployHook }}
        run: curl -X POST -d {} "$NETLIFY_DEPLOY_HOOK"
